# permissions for end users to view elasticsearches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearch-viewer-role
rules:
- apiGroups:
  - logging.openshift.io
  resources:
  - elasticsearches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.openshift.io
  resources:
  - elasticsearches/status
  verbs:
  - get
