# permissions for end users to edit kibanas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kibana-editor-role
rules:
- apiGroups:
  - logging.openshift.io
  resources:
  - kibanas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.openshift.io
  resources:
  - kibanas/status
  verbs:
  - get
