apiVersion: "logging.openshift.io/v1"
kind: "Elasticsearch"
metadata:
  name: "elasticsearch"
spec:
  managementState: "Managed"
  nodeSpec:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
  nodes:
  - nodeCount: 1
    roles: ["client", "data", "master"]
    storage:
      size: 20G
  redundancyPolicy: ZeroRedundancy
  indexManagement:
    policies:
    - name: infra-policy
      pollInterval: 30m
      phases:
        hot:
          actions:
            rollover:
              maxAge:   8h
        delete:
          minAge: 2d
    mappings:
    - name:  infra
      policyRef: infra-policy
      aliases: ["infra", "logs.infra"]