apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: elasticsearch-operator
  name: elasticsearch-operator-metrics-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: elasticsearch-operator
  type: ClusterIP
status:
  loadBalancer: {}
